language: android

# https://docs.travis-ci.com/user/languages/android/
# https://developer.android.com/studio/releases/build-tools
# XXX: keep min & max versions in sync with `./app/build.gradle`
android:
  components:
    - android-28
    - build-tools-28.0.3
    - platform-tools
    - tools
